server:
  servlet:
    context-path: /login
mybatis:
  mapper-locations: classpath:com/example/wcfweb/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/mysql
  redis:
    host: localhost
    port: 6379
